print("=== Анализ последовательности ДНК ===")
dna = input("Введите последовательность ДНК: ")
dna_upper = dna.upper()
print(f"Последовательность в верхнем регистре: {dna_upper}")
count_A = dna.count("A")
count_T = dna.count("T")
count_G = dna.count("G")
count_C = dna.count("C")
total = len(dna_upper)
print("Подсчёт нуклеотидов: ")
print(f"A: {count_A}")
print(f"T: {count_T}")
print(f"G: {count_G}")
print(f"C: {count_C}")
print(f"\nОбщая длина: {total} нуклеотидов")
